export const accountCopy = {
  ru: {
    open: "Закрепить имя / Войти", player: "Игрок", protected: "Имя закреплено", register: "Закрепить имя", login: "Войти", logout: "Выйти",
    intro: "Имя и пароль откроют ваши опубликованные рекорды на любом устройстве. Почта не нужна.",
    existing: "Если вы уже публиковали результат, закрепите имя в том же браузере — рекорды останутся с вами.",
    name: "Имя игрока", password: "Пароль", current: "Текущий пароль", newPassword: "Новый пароль", confirm: "Повторите пароль",
    hint: "От 15 до 128 символов. Можно использовать длинную фразу.",
    forgot: "Забыли пароль?", recover: "Восстановить доступ", recoveryInput: "Код восстановления", recoveryIntro: "Введите имя, сохранённый код и новый пароль. Старый код и входы на других устройствах перестанут работать.",
    change: "Сменить пароль и код", changeNote: "Вы получите новый код восстановления. Входы на других устройствах завершатся.",
    saving: "Подождите…", loading: "Проверяем вход…", retry: "Повторить", unavailable: "Не удалось связаться с сервером. Попробуйте ещё раз. Если имя уже закрепилось, войдите с заданным паролем.",
    taken: "Имя уже занято. Если оно ваше, войдите или закрепите его в браузере, где публиковали рекорды.",
    credentials: "Имя или пароль не подошли.", invalidRecovery: "Имя или код восстановления не подошли.",
    mismatch: "Пароли не совпадают.", invalidName: "Имя должно содержать от 1 до 32 знаков без служебных символов.",
    limited: "Слишком много попыток. Попробуйте через 15 минут.", busy: "Сервер занят. Подождите несколько секунд и повторите.",
    success: "Вход выполнен. Ваши опубликованные рекорды доступны.", signedOut: "Вы вышли. Можно продолжать как гость.",
    already: "В этом браузере уже выполнен вход. Имя игрока обновлено.",
    recoveryTitle: "Сохраните код восстановления", recoveryNote: "Код показывается один раз и позволяет сменить пароль. Сохраните его отдельно и никому не передавайте. Без пароля и кода восстановить доступ не получится.",
    copy: "Скопировать код", copied: "Код скопирован", manual: "Скопируйте выделенный код", download: "Скачать код", saved: "Я сохранил код", cancel: "Отмена",
  },
  en: {
    open: "Reserve a name / Sign in", player: "Player", protected: "Name reserved", register: "Reserve my name", login: "Sign in", logout: "Sign out",
    intro: "Your name and password unlock your published records on any device. No email needed.",
    existing: "Already published a score? Reserve your name in that same browser to keep your records.",
    name: "Player name", password: "Password", current: "Current password", newPassword: "New password", confirm: "Repeat password",
    hint: "15 to 128 characters. A long phrase works well.",
    forgot: "Forgot your password?", recover: "Recover access", recoveryInput: "Recovery code", recoveryIntro: "Enter your name, saved code and a new password. Your old code and sessions on other devices will stop working.",
    change: "Change password and code", changeNote: "You will receive a new recovery code. Sessions on other devices will end.",
    saving: "Please wait…", loading: "Checking sign-in…", retry: "Retry", unavailable: "Could not reach the server. Try again. If your name was already reserved, sign in with the password you chose.",
    taken: "This name is taken. If it is yours, sign in or reserve it in the browser where you published your scores.",
    credentials: "The name or password did not match.", invalidRecovery: "The name or recovery code did not match.",
    mismatch: "Passwords do not match.", invalidName: "Use 1 to 32 characters without control characters.",
    limited: "Too many attempts. Try again in 15 minutes.", busy: "The server is busy. Wait a few seconds and try again.",
    success: "Signed in. Your published records are available.", signedOut: "Signed out. You can keep playing as a guest.",
    already: "This browser is already signed in. The player name has been updated.",
    recoveryTitle: "Save your recovery code", recoveryNote: "This code is shown once and can reset your password. Keep it separately and do not share it. Without your password or code, access cannot be recovered.",
    copy: "Copy code", copied: "Code copied", manual: "Copy the selected code", download: "Download code", saved: "I saved the code", cancel: "Cancel",
  },
} as const;
