export const copy = {
  ru: {
    bonusNames: { gates: "Отметки", edge: "По краю", speed: "Скорость", rhythm: "Ритм", drop: "Высокое падение", shortcut: "Срезка" },
    modes: "Выбрать режим",
    choose: "У каждой дороги своя форма.",
    menuTabs: "Трассы", modeTab: "Режимы", popularTab: "Популярные трассы",
    popularNote: "20 трасс с наибольшим числом игроков, опубликовавших результат. Каждый игрок учитывается один раз.",
    popularEmpty: "Здесь появятся трассы с опубликованными результатами. Завершите заезд и добавьте свой в таблицу.",
    popularLoading: "Ищем дороги с попутчиками…", popularError: "Не удалось загрузить трассы.",
    popularAll: "Все", popularFinite: "Уровни", popularEndless: "Бесконечные",
    popularPlayers: "Игроков", popularBest: "Рекорд", popularPlay: "Играть", popularFilter: "Тип трассы",
    levels: "Проходить уровни",
    endless: "Бесконечная дорога",
    seedMode: "Ввести сид",
    practiceHint: "Знакомые четыре витка",
    levelsHint: "Продолжить с уровня",
    endlessHint: "Без финиша. Держитесь как можно дольше.",
    seedHint: "Код карты или ссылка на неё",
    seedError: "Не удалось прочитать сид. Нужен код вида EGG1-R-2-ABC или ссылка на карту.",
    openSeed: "Открыть карту",
    saved: "Сохранённые карты",
    remove: "Убрать",
    code: "Сид карты",
    copyCode: "Копировать код",
    copyLink: "Ссылка",
    save: "Сохранить",
    savedOne: "Сохранено",
    copied: "Скопировано",
    copyManually: "Скопируйте выделенный текст",
    storageError: "Браузер не разрешил сохранение. Скопируйте код карты.",
    overview: "Осмотреть ещё раз",
    overviewStart: "Подлететь и начать",
    overviewDrag: "Вращайте карту пальцем или мышью в любую сторону. На клавиатуре — стрелки; пробел — начать.",
    overviewReset: "Сбросить обзор",
    endlessView: "Дорога продолжается за горизонтом",
    calibrate: "Калибровать наклон",
    calibrateShort: "Ноль",
    calibrated: "Откалибровано",
    tiltNote: "Наклон меняет только камеру. Держите телефон удобно и нажмите «Калибровать наклон».",
    help: "Ритм и бонусные очки",
    rhythmHelp: "Слегка раскачивайте яйцо влево-вправо обычными поправками курса. Попадать в момент не нужно: первый удачный перекат уже даёт разгон и короткий звук, если он включён. Можно отпускать управление между поворотами. После двух секунд без перекатов разгон постепенно уходит; в полёте ритм сохраняется без прибавки.",
    rhythmStart: "Раскачивайте ← →",
    rhythmAir: "Сохранён в полёте",
    jump: "Прыжок", jumpUsed: "Прыжок использован",
    jumpHelp: "Один прыжок на попытку: кнопка ↑ или пробел. Работает и в воздухе — гасит падение, подбрасывает яйцо и снижает горизонтальную скорость на четверть, чтобы было легче вернуться на дорогу.",
    boost: "к скорости",
    gates: "Отметки",
    distance: "метров",
    scoreBreakdown: "За что получены очки",
    gateRule: "Отметка: +100 очков",
    edgeRule: "Край дороги: +14 очков за метр",
    speedRule: "Быстрее 83 км/ч: до +20 очков за метр",
    rhythmRule: "Ритм от двух перекатов: +2 × серия за метр, до +20",
    dropRule: "Падение от 12 м: +3 очка за метр высоты после приземления",
    shortcutRule: "Срезка: +35 за пропущенную отметку",
    fairRule: "Бонусы начисляются за движение вперёд. Повторный проезд того же места очков не добавляет.",
    seedFinished: "Карта пройдена. Можно повторить её или выбрать другой режим.",
    trackBest: "Ваш рекорд трассы",
    leaderboard: "Таблица этой трассы",
    recordsLoading: "Загружаем рекорды…",
    recordsError: "Таблица пока недоступна. Можно продолжать играть.",
    tryAgain: "Повторить",
    recordsEmpty: "Первый результат ещё ждёт своего имени.",
    recordsNote: "Лучший опубликованный заезд каждого игрока на этом сиде. При равных очках место общее.",
    player: "Игрок", you: "вы", yourPlace: "Ваше место",
    playerName: "Имя в таблице", namePlaceholder: "Как вас записать?",
    publish: "В таблицу", publishing: "Сохраняем…", published: "Ваш рекорд в таблице",
    publishNote: "Имя и результат видны всем. Гость запоминается в этом браузере. Чтобы входить на других устройствах, закрепите имя в меню игрока.",
    publishAccountNote: "Результат будет опубликован под вашим закреплённым именем. Рекорды доступны после входа на любом устройстве.",
    accountChanged: "Вход в этом браузере изменился. Проверьте имя и повторите отправку — заезд сохранён.",
    nameTaken: "Имя уже занято. Войдите, если оно ваше, или выберите другое. Результат заезда сохранён.",
    publishError: "Не удалось отправить. Проверьте имя и соединение, затем повторите. Личный рекорд сохранён в браузере.",
    publishLimited: "Слишком много отправок. Подождите минуту и повторите.",
    publicClose: "К странице игры",
    moreGames: "Больше испытаний доступно адептам.",
    initiation: "Пройти Инициацию →",

    title: "Путь формы", kicker: "Третье испытание", intro: "Удерживайте яйцо на дороге. Падайте на нижние витки, чтобы срезать путь.",
    character: "Небольшие перекаты влево-вправо дают разгон. Удачный перекат отзывается коротким звуком, если он включён.",
    controls: "Касание слева или справа — мягкий поворот. Потяните палец в сторону: дальше — сильнее. Можно менять направление, не отрывая палец.", keyboard: "← → или A / D: коротко — мягко, удерживать — сильнее · Пробел — прыжок · P — пауза · R — заново · F — полный экран",
    fullscreenEnter: "На весь экран", fullscreenExit: "Выйти из полного экрана",
    fullscreenInstall: "На iPhone откройте страницу игры в Safari → «Поделиться» → «На экран Домой». Запускайте игру с этой иконки — панели браузера не будут закрывать дорогу.",
    fullscreenUnavailable: "Браузер не разрешил полный экран. Попробуйте открыть игру напрямую в Safari, Chrome или Firefox.",
    fullscreenGamePage: "Открыть страницу игры →",
    start: "Начать спуск", loading: "Дорога принимает форму…", close: "К испытаниям", pause: "Пауза", resume: "Продолжить",
    paused: "Температурная Пауза", pausedText: "Дорога подождёт. Продолжайте, когда будете готовы.",
    over: "Форма потеряна", overText: "Новая попытка начинается с первого витка.",
    finished: "Путь пройден", finishedText: "Следующая дорога примет новую форму.",
    tutorial: "Учебная трасса", level: "Уровень", next: "Следующая дорога", practice: "Вернуться к учебной",
    flyby: "Взгляните на дорогу", skipFlyby: "К спуску", rhythm: "Ритм", speedUnit: "км/ч",
    look: "Обзор", lookDrag: "Потяните и удерживайте для плавного обзора до 200° в каждую сторону", lookHint: "Потяните ◎ в сторону и удерживайте или нажмите Q / E. Камера поворачивается постепенно, медленнее к краям обзора. Отпустите, чтобы смотреть вперёд.",
    gyroOff: "Обзор наклоном", gyroOn: "Наклон включён", gyroWaiting: "Ожидаем датчик…", gyroMissing: "Датчик недоступен. Для обзора потяните ◎.",
    retry: "Ещё один спуск", best: "Рекорд трассы", score: "Очки", skipped: "Срезано", bestSkip: "Лучшая срезка",
    newBest: "Новый рекорд", air: "Найдите дорогу", shortcut: "Срезано отметок", left: "Повернуть влево", right: "Повернуть вправо",
    soundOn: "Звук включён", soundOff: "Звук выключен", error: "Не удалось открыть дорогу", errorText: "Попробуйте открыть игру снова в браузере с поддержкой 3D-графики.",
  },
  en: {
    bonusNames: { gates: "Gates", edge: "On the edge", speed: "Speed", rhythm: "Rhythm", drop: "High drop", shortcut: "Shortcut" },
    modes: "Choose a mode",
    choose: "Every road has its own form.",
    menuTabs: "Roads", modeTab: "Modes", popularTab: "Popular roads",
    popularNote: "The 20 roads with the most players who published a score. Each player counts once.",
    popularEmpty: "Roads with published scores will appear here. Finish a run and add yours to the board.",
    popularLoading: "Finding roads with fellow travellers…", popularError: "Could not load roads.",
    popularAll: "All", popularFinite: "Levels", popularEndless: "Endless",
    popularPlayers: "Players", popularBest: "Record", popularPlay: "Play", popularFilter: "Road type",
    levels: "Play through levels",
    endless: "Endless road",
    seedMode: "Enter a seed",
    practiceHint: "The familiar four turns",
    levelsHint: "Continue from level",
    endlessHint: "No finish line. Stay on as long as you can.",
    seedHint: "Map code or link",
    seedError: "Could not read this seed. Use a code such as EGG1-R-2-ABC or a map link.",
    openSeed: "Open map",
    saved: "Saved maps",
    remove: "Remove",
    code: "Map seed",
    copyCode: "Copy code",
    copyLink: "Link",
    save: "Save",
    savedOne: "Saved",
    copied: "Copied",
    copyManually: "Copy the selected text",
    storageError: "The browser could not save this map. Copy its code instead.",
    overview: "Look at the map again",
    overviewStart: "Fly in and start",
    overviewDrag: "Drag the map in any direction with a finger or mouse. Keyboard: arrow keys to rotate, Space to start.",
    overviewReset: "Reset view",
    endlessView: "The road continues beyond the horizon",
    calibrate: "Calibrate tilt",
    calibrateShort: "Centre",
    calibrated: "Calibrated",
    tiltNote: "Tilt changes only the camera. Hold your phone comfortably and press Calibrate tilt.",
    help: "Rhythm and bonus points",
    rhythmHelp: "Gently rock the egg left and right with normal steering corrections. No timing cue to follow: the first good stroke gives a boost and a brief tone if sound is on. You can release the controls between turns. After two seconds without a stroke, the boost gradually fades; in the air, rhythm is held without growing.",
    rhythmStart: "Rock gently ← →",
    rhythmAir: "Held in the air",
    jump: "Jump", jumpUsed: "Jump used",
    jumpHelp: "One jump per attempt: tap the ↑ button or press Space. It works in the air too, stopping the fall, lifting the egg and cutting horizontal speed by a quarter to make getting back to the road easier.",
    boost: "extra speed",
    gates: "Gates",
    distance: "metres",
    scoreBreakdown: "Points breakdown",
    gateRule: "Gate: +100 points",
    edgeRule: "Road edge: +14 points per metre",
    speedRule: "Above 83 km/h: up to +20 points per metre",
    rhythmRule: "Rhythm from two strokes: +2 × chain per metre, up to +20",
    dropRule: "Drop of 12 m or more: +3 points per metre of height after landing",
    shortcutRule: "Shortcut: +35 per skipped gate",
    fairRule: "Bonuses require new forward progress. Riding the same section again earns no extra points.",
    seedFinished: "Map complete. Replay it or choose another mode.",
    trackBest: "Your best on this road",
    leaderboard: "This road’s leaderboard",
    recordsLoading: "Loading records…",
    recordsError: "The leaderboard is unavailable. You can keep playing.",
    tryAgain: "Retry",
    recordsEmpty: "The first result is waiting for a name.",
    recordsNote: "Each player’s best published run on this seed. Equal scores share a rank.",
    player: "Player", you: "you", yourPlace: "Your rank",
    playerName: "Leaderboard name", namePlaceholder: "What shall we call you?",
    publish: "Publish score", publishing: "Saving…", published: "Your best is on the board",
    publishNote: "Your name and score are public. Guests are remembered in this browser. Reserve your name in the player menu to sign in on other devices.",
    publishAccountNote: "Your score will be published under your reserved name. Sign in on any device to access your records.",
    accountChanged: "The signed-in player changed in this browser. Check the name and submit again — your run is still saved.",
    nameTaken: "This name is taken. Sign in if it is yours, or choose another. Your run is still saved.",
    publishError: "Could not publish. Check your name and connection, then retry. Your personal best is saved in this browser.",
    publishLimited: "Too many submissions. Wait a minute and retry.",
    publicClose: "Back to the game page",
    moreGames: "More trials await adepts.",
    initiation: "Take the Initiation →",

    title: "Path of Form", kicker: "The third trial", intro: "Keep the egg on the road. Land on the lower turns to take a shortcut.",
    character: "Small left-right strokes build speed. A good stroke plays a brief tone if sound is on.",
    controls: "Touch the left or right side for a gentle turn. Drag sideways: further means stronger. You can change direction without lifting your finger.", keyboard: "← → or A / D: tap gently, hold for more · Space to jump · P to pause · R to restart · F for fullscreen",
    fullscreenEnter: "Enter fullscreen", fullscreenExit: "Exit fullscreen",
    fullscreenInstall: "On iPhone, open the game page in Safari → Share → Add to Home Screen. Launch it from that icon to keep browser bars off the road.",
    fullscreenUnavailable: "The browser did not allow fullscreen. Try opening the game directly in Safari, Chrome or Firefox.",
    fullscreenGamePage: "Open the game page →",
    start: "Begin the descent", loading: "The road is taking form…", close: "Back to trials", pause: "Pause", resume: "Continue",
    paused: "A Temperature Pause", pausedText: "The road will wait. Continue when you are ready.",
    over: "Form lost", overText: "The next attempt begins at the first turn.",
    finished: "The path is complete", finishedText: "The next road will take a new form.",
    tutorial: "Practice road", level: "Level", next: "The next road", practice: "Return to practice",
    flyby: "Take a look at the road", skipFlyby: "Start rolling", rhythm: "Rhythm", speedUnit: "km/h",
    look: "Look", lookDrag: "Drag and hold to look smoothly up to 200° either way", lookHint: "Drag ◎ sideways and hold, or hold Q / E. The camera turns gradually, slowing near the ends of its range. Release to face forward.",
    gyroOff: "Look by tilting", gyroOn: "Tilt enabled", gyroWaiting: "Waiting for sensor…", gyroMissing: "Sensor unavailable. Drag ◎ to look around.",
    retry: "Another descent", best: "Road best", score: "Points", skipped: "Skipped", bestSkip: "Best shortcut",
    newBest: "New best", air: "Find the road", shortcut: "Gates skipped", left: "Steer left", right: "Steer right",
    soundOn: "Sound on", soundOff: "Sound off", error: "The road could not open", errorText: "Try opening the game again in a browser that supports 3D graphics.",
  },
} as const;
