export const copy = {
  ru: {
    bonusNames: { gates: "Отметки", edge: "По краю", speed: "Скорость", rhythm: "Ритм", drop: "Высокое падение", shortcut: "Срезка" },
    modes: "Выбрать режим",
    choose: "У каждой дороги своя форма.",
    levels: "Проходить уровни",
    endless: "Бесконечная дорога",
    seedMode: "Ввести сид",
    practiceHint: "Знакомые четыре витка",
    levelsHint: "Продолжить с уровня",
    endlessHint: "Без финиша. Держитесь как можно дольше.",
    seedHint: "Код карты или ссылка на неё",
    seedError: "Не удалось прочитать сид. Нужен код вида EGG1-R-2-ABC или ссылка на карту.",
    openSeed: "Открыть карту",
    saved: "Сохранённые карты",
    remove: "Убрать",
    code: "Сид карты",
    copyCode: "Копировать код",
    copyLink: "Ссылка",
    save: "Сохранить",
    savedOne: "Сохранено",
    copied: "Скопировано",
    copyManually: "Скопируйте выделенный текст",
    storageError: "Браузер не разрешил сохранение. Скопируйте код карты.",
    overview: "Осмотреть ещё раз",
    overviewStart: "Подлететь и начать",
    endlessView: "Дорога продолжается за горизонтом",
    calibrate: "Калибровать наклон",
    calibrateShort: "Ноль",
    calibrated: "Откалибровано",
    tiltNote: "Наклон меняет только камеру. Держите телефон удобно и нажмите «Калибровать наклон».",
    help: "Ритм и бонусные очки",
    rhythmHelp: "Удерживайте сторону примерно полсекунды, пока яйцо перекатывается. Когда стрелка загорится — меняйте сторону. Продолжайте чередовать: серия даёт скорость и очки.",
    rhythmStart: "Начните с ← или →",
    rhythmHold: "Держите",
    rhythmSwitch: "Сейчас",
    rhythmLate: "Смените сторону",
    rhythmAir: "Вернитесь на дорогу",
    boost: "к скорости",
    gates: "Отметки",
    distance: "метров",
    scoreBreakdown: "За что получены очки",
    gateRule: "Отметка: +100 очков",
    edgeRule: "Край дороги: +14 очков за метр",
    speedRule: "Быстрее 83 км/ч: до +20 очков за метр",
    rhythmRule: "Ритм от двух перекатов: +2 × серия за метр, до +20",
    dropRule: "Падение от 12 м: +3 очка за метр высоты после приземления",
    shortcutRule: "Срезка: +35 за пропущенную отметку",
    fairRule: "Бонусы начисляются за движение вперёд. Повторный проезд того же места очков не добавляет.",
    seedFinished: "Карта пройдена. Можно повторить её или выбрать другой режим.",

    title: "Путь формы", kicker: "Третье испытание", intro: "Удерживайте яйцо на дороге. Падайте на нижние витки, чтобы срезать путь.",
    character: "Держите сторону, затем меняйте её по подсказке. Ритм даёт скорость и бонусные очки.",
    controls: "Удерживайте левую или правую сторону экрана", keyboard: "← → или A / D · P — пауза · R — заново",
    start: "Начать спуск", loading: "Дорога принимает форму…", close: "К испытаниям", pause: "Пауза", resume: "Продолжить",
    paused: "Температурная Пауза", pausedText: "Дорога подождёт. Продолжайте, когда будете готовы.",
    over: "Форма потеряна", overText: "Новая попытка начинается с первого витка.",
    finished: "Путь пройден", finishedText: "Следующая дорога примет новую форму.",
    tutorial: "Учебная трасса", level: "Уровень", next: "Следующая дорога", practice: "Вернуться к учебной",
    flyby: "Взгляните на дорогу", skipFlyby: "К спуску", rhythm: "Ритм", speedUnit: "км/ч",
    look: "Обзор", lookDrag: "Обзор: удерживайте и двигайте пальцем", lookHint: "Обзор: потяните ◎ или удерживайте Q / E",
    gyroOff: "Обзор наклоном", gyroOn: "Наклон включён", gyroWaiting: "Ожидаем датчик…", gyroMissing: "Датчик недоступен. Для обзора потяните ◎.",
    retry: "Ещё один спуск", best: "Рекорд", score: "Очки", skipped: "Срезано", bestSkip: "Лучшая срезка",
    newBest: "Новый рекорд", air: "Найдите дорогу", shortcut: "Срезано отметок", left: "Повернуть влево", right: "Повернуть вправо",
    soundOn: "Звук включён", soundOff: "Звук выключен", error: "Не удалось открыть дорогу", errorText: "Попробуйте открыть игру снова в браузере с поддержкой 3D-графики.",
  },
  en: {
    bonusNames: { gates: "Gates", edge: "On the edge", speed: "Speed", rhythm: "Rhythm", drop: "High drop", shortcut: "Shortcut" },
    modes: "Choose a mode",
    choose: "Every road has its own form.",
    levels: "Play through levels",
    endless: "Endless road",
    seedMode: "Enter a seed",
    practiceHint: "The familiar four turns",
    levelsHint: "Continue from level",
    endlessHint: "No finish line. Stay on as long as you can.",
    seedHint: "Map code or link",
    seedError: "Could not read this seed. Use a code such as EGG1-R-2-ABC or a map link.",
    openSeed: "Open map",
    saved: "Saved maps",
    remove: "Remove",
    code: "Map seed",
    copyCode: "Copy code",
    copyLink: "Link",
    save: "Save",
    savedOne: "Saved",
    copied: "Copied",
    copyManually: "Copy the selected text",
    storageError: "The browser could not save this map. Copy its code instead.",
    overview: "Look at the map again",
    overviewStart: "Fly in and start",
    endlessView: "The road continues beyond the horizon",
    calibrate: "Calibrate tilt",
    calibrateShort: "Centre",
    calibrated: "Calibrated",
    tiltNote: "Tilt changes only the camera. Hold your phone comfortably and press Calibrate tilt.",
    help: "Rhythm and bonus points",
    rhythmHelp: "Hold a side for about half a second while the egg rolls. When the arrow lights up, switch sides. Keep alternating: the chain earns speed and points.",
    rhythmStart: "Start with ← or →",
    rhythmHold: "Hold",
    rhythmSwitch: "Now",
    rhythmLate: "Switch sides",
    rhythmAir: "Return to the road",
    boost: "extra speed",
    gates: "Gates",
    distance: "metres",
    scoreBreakdown: "Points breakdown",
    gateRule: "Gate: +100 points",
    edgeRule: "Road edge: +14 points per metre",
    speedRule: "Above 83 km/h: up to +20 points per metre",
    rhythmRule: "Rhythm from two strokes: +2 × chain per metre, up to +20",
    dropRule: "Drop of 12 m or more: +3 points per metre of height after landing",
    shortcutRule: "Shortcut: +35 per skipped gate",
    fairRule: "Bonuses require new forward progress. Riding the same section again earns no extra points.",
    seedFinished: "Map complete. Replay it or choose another mode.",

    title: "Path of Form", kicker: "The third trial", intro: "Keep the egg on the road. Land on the lower turns to take a shortcut.",
    character: "Hold a side, then switch when prompted. Rhythm earns speed and bonus points.",
    controls: "Hold the left or right side of the screen", keyboard: "← → or A / D · P to pause · R to restart",
    start: "Begin the descent", loading: "The road is taking form…", close: "Back to trials", pause: "Pause", resume: "Continue",
    paused: "A Temperature Pause", pausedText: "The road will wait. Continue when you are ready.",
    over: "Form lost", overText: "The next attempt begins at the first turn.",
    finished: "The path is complete", finishedText: "The next road will take a new form.",
    tutorial: "Practice road", level: "Level", next: "The next road", practice: "Return to practice",
    flyby: "Take a look at the road", skipFlyby: "Start rolling", rhythm: "Rhythm", speedUnit: "km/h",
    look: "Look", lookDrag: "Look around: hold and drag", lookHint: "Look around: drag ◎ or hold Q / E",
    gyroOff: "Look by tilting", gyroOn: "Tilt enabled", gyroWaiting: "Waiting for sensor…", gyroMissing: "Sensor unavailable. Drag ◎ to look around.",
    retry: "Another descent", best: "Best", score: "Points", skipped: "Skipped", bestSkip: "Best shortcut",
    newBest: "New best", air: "Find the road", shortcut: "Gates skipped", left: "Steer left", right: "Steer right",
    soundOn: "Sound on", soundOff: "Sound off", error: "The road could not open", errorText: "Try opening the game again in a browser that supports 3D graphics.",
  },
} as const;
