export const copy = {
  ru: {
    bonusNames: { gates: "Отметки", edge: "По краю", speed: "Скорость", rhythm: "Ритм", drop: "Высокое падение", shortcut: "Срезка" },
    modes: "Выбрать режим",
    choose: "У каждой дороги своя форма.",
    menuTabs: "Трассы", modeTab: "Режимы", popularTab: "Популярные трассы",
    popularNote: "20 трасс с наибольшим числом игроков, опубликовавших результат. Каждый игрок учитывается один раз.",
    popularEmpty: "Здесь появятся трассы с опубликованными результатами. Завершите заезд и добавьте свой в таблицу.",
    popularLoading: "Ищем дороги с попутчиками…", popularError: "Не удалось загрузить трассы.",
    popularAll: "Все", popularFinite: "Уровни", popularEndless: "Бесконечные",
    popularPlayers: "Игроков", popularBest: "Рекорд", popularPlay: "Играть", popularFilter: "Тип трассы",
    levels: "Проходить уровни",
    endless: "Бесконечная дорога",
    seedMode: "Ввести сид",
    practiceHint: "Знакомые четыре витка",
    levelsHint: "Продолжить с уровня",
    endlessHint: "Без финиша. Держитесь как можно дольше.",
    seedHint: "Код карты или ссылка на неё",
    seedError: "Не удалось прочитать сид. Нужен код вида EGG1-R-2-ABC или ссылка на карту.",
    openSeed: "Открыть карту",
    saved: "Сохранённые карты",
    remove: "Убрать",
    code: "Сид карты",
    copyCode: "Копировать код",
    copyLink: "Ссылка",
    save: "Сохранить",
    savedOne: "Сохранено",
    copied: "Скопировано",
    copyManually: "Скопируйте выделенный текст",
    storageError: "Браузер не разрешил сохранение. Скопируйте код карты.",
    overview: "Осмотреть ещё раз",
    overviewStart: "Подлететь и начать",
    endlessView: "Дорога продолжается за горизонтом",
    calibrate: "Калибровать наклон",
    calibrateShort: "Ноль",
    calibrated: "Откалибровано",
    tiltNote: "Наклон меняет только камеру. Держите телефон удобно и нажмите «Калибровать наклон».",
    help: "Ритм и бонусные очки",
    rhythmHelp: "Удерживайте сторону примерно полсекунды, пока яйцо перекатывается. Когда стрелка загорится — меняйте сторону. Продолжайте чередовать: серия даёт скорость и очки. В полёте ритм сохраняется, но не растёт; продолжайте после приземления.",
    rhythmStart: "Начните с ← или →",
    rhythmHold: "Держите",
    rhythmSwitch: "Сейчас",
    rhythmLate: "Смените сторону",
    rhythmAir: "Ритм сохранён · в полёте",
    boost: "к скорости",
    gates: "Отметки",
    distance: "метров",
    scoreBreakdown: "За что получены очки",
    gateRule: "Отметка: +100 очков",
    edgeRule: "Край дороги: +14 очков за метр",
    speedRule: "Быстрее 83 км/ч: до +20 очков за метр",
    rhythmRule: "Ритм от двух перекатов: +2 × серия за метр, до +20",
    dropRule: "Падение от 12 м: +3 очка за метр высоты после приземления",
    shortcutRule: "Срезка: +35 за пропущенную отметку",
    fairRule: "Бонусы начисляются за движение вперёд. Повторный проезд того же места очков не добавляет.",
    seedFinished: "Карта пройдена. Можно повторить её или выбрать другой режим.",
    trackBest: "Ваш рекорд трассы",
    leaderboard: "Таблица этой трассы",
    recordsLoading: "Загружаем рекорды…",
    recordsError: "Таблица пока недоступна. Можно продолжать играть.",
    tryAgain: "Повторить",
    recordsEmpty: "Первый результат ещё ждёт своего имени.",
    recordsNote: "Лучший опубликованный заезд каждого игрока на этом сиде. При равных очках место общее.",
    player: "Игрок", you: "вы", yourPlace: "Ваше место",
    playerName: "Имя в таблице", namePlaceholder: "Как вас записать?",
    publish: "В таблицу", publishing: "Сохраняем…", published: "Ваш рекорд в таблице",
    publishNote: "Имя и результат видны всем. Имя закрепляется за этим браузером и едино для всех трасс. После очистки cookie или на другом устройстве доступ к нему не сохранится.",
    nameTaken: "Это имя уже занято. Выберите другое — результат заезда сохранён.",
    publishError: "Не удалось отправить. Проверьте имя и соединение, затем повторите. Личный рекорд сохранён в браузере.",
    publishLimited: "Слишком много отправок. Подождите минуту и повторите.",
    publicClose: "К странице игры",
    moreGames: "Больше испытаний доступно адептам.",
    initiation: "Пройти Инициацию →",

    title: "Путь формы", kicker: "Третье испытание", intro: "Удерживайте яйцо на дороге. Падайте на нижние витки, чтобы срезать путь.",
    character: "Держите сторону, затем меняйте её по подсказке. Ритм даёт скорость и бонусные очки.",
    controls: "Удерживайте левую или правую сторону экрана", keyboard: "← → или A / D · P — пауза · R — заново",
    start: "Начать спуск", loading: "Дорога принимает форму…", close: "К испытаниям", pause: "Пауза", resume: "Продолжить",
    paused: "Температурная Пауза", pausedText: "Дорога подождёт. Продолжайте, когда будете готовы.",
    over: "Форма потеряна", overText: "Новая попытка начинается с первого витка.",
    finished: "Путь пройден", finishedText: "Следующая дорога примет новую форму.",
    tutorial: "Учебная трасса", level: "Уровень", next: "Следующая дорога", practice: "Вернуться к учебной",
    flyby: "Взгляните на дорогу", skipFlyby: "К спуску", rhythm: "Ритм", speedUnit: "км/ч",
    look: "Обзор", lookDrag: "Обзор: удерживайте и двигайте пальцем", lookHint: "Обзор: потяните ◎ или удерживайте Q / E",
    gyroOff: "Обзор наклоном", gyroOn: "Наклон включён", gyroWaiting: "Ожидаем датчик…", gyroMissing: "Датчик недоступен. Для обзора потяните ◎.",
    retry: "Ещё один спуск", best: "Рекорд трассы", score: "Очки", skipped: "Срезано", bestSkip: "Лучшая срезка",
    newBest: "Новый рекорд", air: "Найдите дорогу", shortcut: "Срезано отметок", left: "Повернуть влево", right: "Повернуть вправо",
    soundOn: "Звук включён", soundOff: "Звук выключен", error: "Не удалось открыть дорогу", errorText: "Попробуйте открыть игру снова в браузере с поддержкой 3D-графики.",
  },
  en: {
    bonusNames: { gates: "Gates", edge: "On the edge", speed: "Speed", rhythm: "Rhythm", drop: "High drop", shortcut: "Shortcut" },
    modes: "Choose a mode",
    choose: "Every road has its own form.",
    menuTabs: "Roads", modeTab: "Modes", popularTab: "Popular roads",
    popularNote: "The 20 roads with the most players who published a score. Each player counts once.",
    popularEmpty: "Roads with published scores will appear here. Finish a run and add yours to the board.",
    popularLoading: "Finding roads with fellow travellers…", popularError: "Could not load roads.",
    popularAll: "All", popularFinite: "Levels", popularEndless: "Endless",
    popularPlayers: "Players", popularBest: "Record", popularPlay: "Play", popularFilter: "Road type",
    levels: "Play through levels",
    endless: "Endless road",
    seedMode: "Enter a seed",
    practiceHint: "The familiar four turns",
    levelsHint: "Continue from level",
    endlessHint: "No finish line. Stay on as long as you can.",
    seedHint: "Map code or link",
    seedError: "Could not read this seed. Use a code such as EGG1-R-2-ABC or a map link.",
    openSeed: "Open map",
    saved: "Saved maps",
    remove: "Remove",
    code: "Map seed",
    copyCode: "Copy code",
    copyLink: "Link",
    save: "Save",
    savedOne: "Saved",
    copied: "Copied",
    copyManually: "Copy the selected text",
    storageError: "The browser could not save this map. Copy its code instead.",
    overview: "Look at the map again",
    overviewStart: "Fly in and start",
    endlessView: "The road continues beyond the horizon",
    calibrate: "Calibrate tilt",
    calibrateShort: "Centre",
    calibrated: "Calibrated",
    tiltNote: "Tilt changes only the camera. Hold your phone comfortably and press Calibrate tilt.",
    help: "Rhythm and bonus points",
    rhythmHelp: "Hold a side for about half a second while the egg rolls. When the arrow lights up, switch sides. Keep alternating: the chain earns speed and points. In the air, rhythm is held without growing; continue after landing.",
    rhythmStart: "Start with ← or →",
    rhythmHold: "Hold",
    rhythmSwitch: "Now",
    rhythmLate: "Switch sides",
    rhythmAir: "Rhythm held · airborne",
    boost: "extra speed",
    gates: "Gates",
    distance: "metres",
    scoreBreakdown: "Points breakdown",
    gateRule: "Gate: +100 points",
    edgeRule: "Road edge: +14 points per metre",
    speedRule: "Above 83 km/h: up to +20 points per metre",
    rhythmRule: "Rhythm from two strokes: +2 × chain per metre, up to +20",
    dropRule: "Drop of 12 m or more: +3 points per metre of height after landing",
    shortcutRule: "Shortcut: +35 per skipped gate",
    fairRule: "Bonuses require new forward progress. Riding the same section again earns no extra points.",
    seedFinished: "Map complete. Replay it or choose another mode.",
    trackBest: "Your best on this road",
    leaderboard: "This road’s leaderboard",
    recordsLoading: "Loading records…",
    recordsError: "The leaderboard is unavailable. You can keep playing.",
    tryAgain: "Retry",
    recordsEmpty: "The first result is waiting for a name.",
    recordsNote: "Each player’s best published run on this seed. Equal scores share a rank.",
    player: "Player", you: "you", yourPlace: "Your rank",
    playerName: "Leaderboard name", namePlaceholder: "What shall we call you?",
    publish: "Publish score", publishing: "Saving…", published: "Your best is on the board",
    publishNote: "Your name and score are public. Your name belongs to this browser across all roads. Clearing cookies or switching devices loses access to it.",
    nameTaken: "This name is already taken. Choose another — your run is still saved.",
    publishError: "Could not publish. Check your name and connection, then retry. Your personal best is saved in this browser.",
    publishLimited: "Too many submissions. Wait a minute and retry.",
    publicClose: "Back to the game page",
    moreGames: "More trials await adepts.",
    initiation: "Take the Initiation →",

    title: "Path of Form", kicker: "The third trial", intro: "Keep the egg on the road. Land on the lower turns to take a shortcut.",
    character: "Hold a side, then switch when prompted. Rhythm earns speed and bonus points.",
    controls: "Hold the left or right side of the screen", keyboard: "← → or A / D · P to pause · R to restart",
    start: "Begin the descent", loading: "The road is taking form…", close: "Back to trials", pause: "Pause", resume: "Continue",
    paused: "A Temperature Pause", pausedText: "The road will wait. Continue when you are ready.",
    over: "Form lost", overText: "The next attempt begins at the first turn.",
    finished: "The path is complete", finishedText: "The next road will take a new form.",
    tutorial: "Practice road", level: "Level", next: "The next road", practice: "Return to practice",
    flyby: "Take a look at the road", skipFlyby: "Start rolling", rhythm: "Rhythm", speedUnit: "km/h",
    look: "Look", lookDrag: "Look around: hold and drag", lookHint: "Look around: drag ◎ or hold Q / E",
    gyroOff: "Look by tilting", gyroOn: "Tilt enabled", gyroWaiting: "Waiting for sensor…", gyroMissing: "Sensor unavailable. Drag ◎ to look around.",
    retry: "Another descent", best: "Road best", score: "Points", skipped: "Skipped", bestSkip: "Best shortcut",
    newBest: "New best", air: "Find the road", shortcut: "Gates skipped", left: "Steer left", right: "Steer right",
    soundOn: "Sound on", soundOff: "Sound off", error: "The road could not open", errorText: "Try opening the game again in a browser that supports 3D graphics.",
  },
} as const;
